apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: pod-security-nonroot-no-privileged
spec:
  validationActions: [Deny]
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - kyverno
            - argocd
            - longhorn-system
            - falco        # Liệt kê chính xác, không dùng *
            - falco-lab
            - falco-test
            - gitlab-system
            - gitlab-runner
  validations:
    - expression: >
        object.spec.containers.all(c, 
          has(c.securityContext) && has(c.securityContext.runAsNonRoot) && 
          c.securityContext.runAsNonRoot == true
        )
      message: "Container bắt buộc phải khai báo và chạy non-root."
    - expression: >
        object.spec.containers.all(c, 
          !has(c.securityContext) || !has(c.securityContext.privileged) || 
          c.securityContext.privileged == false
        )
      message: "Không cho phép chạy privileged mode."
