apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-sensitive-hostpath
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: disallow-sensitive-hostpath
      match:
        resources:
          kinds: ["Pod"]
      exclude:
        resources:
          namespaces: ["kube-system", "kyverno", "argocd"]
      # Bypass bằng cách gán label cho namespace: policy.kyverno.io/allow-sensitive-hostpath="true"
      preconditions:
        all:
          - key: "{{ request.namespaceLabels.\"policy.kyverno.io/allow-sensitive-hostpath\" || 'false' }}"
            operator: NotEquals
            value: "true"
      validate:
        message: "Không cho phép mount hostPath nhạy cảm (/, /etc, /proc, /sys...). Cần ns label policy.kyverno.io/allow-sensitive-hostpath='true' để bypass."
        foreach:
          - list: "request.object.spec.volumes[?hostPath]"
            deny:
              conditions:
                any:
                  - key: "{{ regex_match('^/$|^/etc($|/)|^/proc($|/)|^/sys($|/)|^/etc/passwd$|^/etc/shadow$', element.hostPath.path) }}"
                    operator: Equals
                    value: true
