apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-requests-limits
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-resources-containers
      match:
        resources:
          kinds: ["Pod"]
      exclude:
        resources:
          namespaces: ["kube-system", "kyverno", "argocd"]
      # Bypass bằng cách gán label cho namespace: policy.kyverno.io/skip-resources="true"
      preconditions:
        all:
          - key: "{{ request.namespaceLabels.\"policy.kyverno.io/skip-resources\" || 'false' }}"
            operator: NotEquals
            value: "true"
      validate:
        message: "Containers phải khai báo resources.requests/limits cpu & memory (hoặc dùng ns label skip-resources='true')"
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    cpu: "?*"
                    memory: "?*"
                  limits:
                    cpu: "?*"
                    memory: "?*"
            =(initContainers):
              - resources:
                  requests:
                    cpu: "?*"
                    memory: "?*"
                  limits:
                    cpu: "?*"
                    memory: "?*"
