apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-probes
  annotations:
    # Chỉ auto-gen cho workload dài hạn, không auto-gen cho Job/CronJob
    pod-policies.kyverno.io/autogen-controllers: Deployment,StatefulSet,DaemonSet
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-probes
      match:
        resources:
          kinds: ["Pod"]
      preconditions:
        all:
          # Không áp dụng ở các namespace hệ thống
          - key: "{{ request.namespace }}"
            operator: AnyNotIn
            value: ["kube-system", "kyverno", "argocd"]
          # Bỏ qua Pod do Job/CronJob tạo (ownerRef là Job)
          - key: "Job"
            operator: AnyNotIn
            value: "{{ request.object.metadata.ownerReferences[].kind || `[]` }}"
      validate:
        message: "Container phải khai báo livenessProbe và readinessProbe (trừ Job/CronJob)."
        pattern:
          spec:
            containers:
              - livenessProbe:
                  periodSeconds: "?*"
                readinessProbe:
                  periodSeconds: "?*"
