apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-probes
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-probes
      match:
        resources:
          kinds:
            - Pod

      # Dùng Preconditions để loại trừ namespace hệ thống + Pod của Job/CronJob
      preconditions:
        all:
          # 1) Bỏ qua các namespace hệ thống
          - key: "{{ request.object.metadata.namespace }}"
            operator: NotIn
            value:
              - kube-system
              - kyverno
              - argocd

          # 2) Bỏ qua Pod thuộc Job/CronJob (thường có label job-name)
          # Nếu label job-name không tồn tại -> '' => vẫn check (Pod thường)
          - key: "{{ request.object.metadata.labels.\"job-name\" || '' }}"
            operator: Equals
            value: ""

      validate:
        message: "Container phải khai báo livenessProbe và readinessProbe (trừ Job/CronJob)."
        pattern:
          spec:
            containers:
              - (name): "*"
                livenessProbe: {}
                readinessProbe: {}
