apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-probes
  annotations:
    pod-policies.kyverno.io/autogen-controllers: Deployment,StatefulSet,DaemonSet
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-probes
      match:
        resources:
          kinds: ["Pod"]
          namespaceSelector:
            matchExpressions:
              - key: policy.tier
                operator: Exists
      preconditions:
        all:
          - key: "Job"
            operator: AnyNotIn
            value: "{{ request.object.metadata.ownerReferences[].kind || `[]` }}"
      validate:
        message: "Container phải khai báo livenessProbe và readinessProbe (trừ Job/CronJob)."
        pattern:
          spec:
            containers:
              - livenessProbe:
                  periodSeconds: "?*"
                readinessProbe:
                  periodSeconds: "?*"
