apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-team-labels
      match:
        resources:
          kinds: ["Pod"]
          namespaceSelector:
            matchExpressions:
              - key: policy.tier
                operator: Exists
      validate:
        message: "Pod phải có label 'owner' và 'env'."
        pattern:
          metadata:
            labels:
              owner: "?*"
              env: "?*"
