apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-imagepullsecrets
spec:
  background: true
  rules:
    - name: add-regcred
      match:
        resources:
          kinds: ["Pod"]
          namespaceSelector:
            matchExpressions:
              - key: policy.tier
                operator: Exists
      mutate:
        patchStrategicMerge:
          spec:
            imagePullSecrets:
              - name: regcred
