apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-firewall-service-signature
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: verify-signature
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "index.docker.io/d4vlin/firewall-service@sha256:*"
          attestors:
            - entries:
                - keys:
                    publicKeys: |
                      -----BEGIN PUBLIC KEY-----
                      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERgxeNxC6iuA3A7NIgrSeokEkX/eY
                      DlhMN+eo63ZnpughAS0t/qxj2+Qj+UlY5/Bewy98mLa+PnMkItw6XWNjsA==
                      -----END PUBLIC KEY-----
          mutateDigest: false
