apiVersion: policies.kyverno.io/v1
kind: ImageValidatingPolicy
metadata:
  name: verify-demo-image-signature
  annotations:
    policies.kyverno.io/title: Verify Demo Image Signature
    policies.kyverno.io/category: Software Supply Chain Security
    policies.kyverno.io/severity: high
spec:
  webhookConfiguration:
    timeoutSeconds: 30
  evaluation:
    background:
      enabled: false
  validationActions:
    - Audit

  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]

  # Bạn cấu hình đoạn này RẤT CHUẨN: Chỉ bắt bẻ các Pod dùng ảnh từ IP này, không làm chết cụm!
  matchImageReferences:
    - glob: "192.168.105.24:32080/demo/*"

  credentials:
    allowInsecureRegistry: true

  attestors:
    - name: cosignkey
      cosign:
        key:
          data: |-
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEpfbmFhkNwTCo468eu0JniiHtM5WG
            DbAFOkI4pI1pANrk5T+mhcJT1HWr9+vBuzdTCPpXL9sgkrqT6sUCGPe2hw==
            -----END PUBLIC KEY-----

  validations:
    - expression: >-
        images.containers.all(name, verifyImageSignatures(images.containers[name], [attestors.cosignkey]) > 0)
      message: "Container chính chưa có chữ ký hợp lệ theo Cosign public key."
    - expression: >-
        images.?initContainers.orValue({}).all(name, verifyImageSignatures(images.initContainers[name], [attestors.cosignkey]) > 0)
      message: "Init Container chưa có chữ ký hợp lệ."
    - expression: >-
        images.?ephemeralContainers.orValue({}).all(name, verifyImageSignatures(images.ephemeralContainers[name], [attestors.cosignkey]) > 0)
      message: "Ephemeral Container chưa có chữ ký hợp lệ."
