apiVersion: policies.kyverno.io/v1
kind: NamespacedValidatingPolicy
metadata:
  name: require-team-label
  namespace: kyverno-demo
spec:
  validationActions: [Deny]
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - message: "Pod phải có label team=<ten-team>."
      expression: "has(object.metadata.labels) && 'team' in object.metadata.labels"
