apiVersion: policies.kyverno.io/v1
kind: NamespacedImageValidatingPolicy
metadata:
  name: verify-images-signed
  namespace: kyverno-demo
spec:
  validationActions: [Deny]
  evaluation:
    background:
      enabled: false
  webhookConfiguration:
    timeoutSeconds: 30
  failurePolicy: Fail

  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]

  matchImageReferences:
    - glob: "d4vlin/firewall-service:*"
    - glob: "docker.io/d4vlin/firewall-service:*"
    - glob: "index.docker.io/d4vlin/firewall-service:*"
    - glob: "d4vlin/firewall-service@sha256:*"
    - glob: "docker.io/d4vlin/firewall-service@sha256:*"
    - glob: "index.docker.io/d4vlin/firewall-service@sha256:*"

  attestors:
    - name: cosignKey
      cosign:
        key:
          data: |
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAERgxeNxC6iuA3A7NIgrSeokEkX/eY
            DlhMN+eo63ZnpughAS0t/qxj2+Qj+UlY5/Bewy98mLa+PnMkItw6XWNjsA==
            -----END PUBLIC KEY-----

  validations:
    - expression: "images.containers.map(image, verifyImageSignatures(image, [attestors.cosignKey])).all(e, e > 0)"
      message: "Image phải được ký (Cosign) bằng khóa được phê duyệt."
